import { PrismaService } from '../../prisma/prisma.service';

/**
 * Seeds 21 badge definitions with en/vi translations.
 * Called from the main seed script.
 */
export async function seedBadges(prisma: PrismaService) {
  const badges = [
    // Activity badges
    {
      code: 'FIRST_TIMER',
      category: 'activity',
      icon: 'emoji_events',
      color: '#4CAF50',
      conditionType: 'total_activities',
      conditionValue: 1,
      rarity: 'COMMON',
      sortOrder: 1,
      en: { name: 'First Timer', description: 'Complete your first activity' },
      vi: { name: 'Bước đầu', description: 'Hoàn thành hoạt động đầu tiên' },
    },
    {
      code: 'GETTING_STARTED',
      category: 'activity',
      icon: 'directions_run',
      color: '#4CAF50',
      conditionType: 'total_activities',
      conditionValue: 5,
      rarity: 'COMMON',
      sortOrder: 2,
      en: { name: 'Getting Started', description: 'Complete 5 activities' },
      vi: { name: 'Khởi động', description: 'Hoàn thành 5 hoạt động' },
    },
    {
      code: 'DEDICATED_10',
      category: 'activity',
      icon: 'fitness_center',
      color: '#2196F3',
      conditionType: 'total_activities',
      conditionValue: 10,
      rarity: 'COMMON',
      sortOrder: 3,
      en: { name: 'Dedicated', description: 'Complete 10 activities' },
      vi: { name: 'Tận tâm', description: 'Hoàn thành 10 hoạt động' },
    },
    {
      code: 'HALF_CENTURY',
      category: 'activity',
      icon: 'military_tech',
      color: '#9C27B0',
      conditionType: 'total_activities',
      conditionValue: 50,
      rarity: 'RARE',
      sortOrder: 4,
      en: { name: 'Half Century', description: 'Complete 50 activities' },
      vi: { name: 'Nửa trăm', description: 'Hoàn thành 50 hoạt động' },
    },
    {
      code: 'CENTURION',
      category: 'activity',
      icon: 'workspace_premium',
      color: '#FF9800',
      conditionType: 'total_activities',
      conditionValue: 100,
      rarity: 'EPIC',
      sortOrder: 5,
      en: { name: 'Centurion', description: 'Complete 100 activities' },
      vi: { name: 'Chiến binh', description: 'Hoàn thành 100 hoạt động' },
    },
    // Streak badges
    {
      code: 'STREAK_3',
      category: 'streak',
      icon: 'local_fire_department',
      color: '#FF5722',
      conditionType: 'streak',
      conditionValue: 3,
      rarity: 'COMMON',
      sortOrder: 10,
      en: { name: '3-Day Streak', description: 'Maintain a 3-day streak' },
      vi: { name: 'Streak 3 ngày', description: 'Duy trì streak 3 ngày' },
    },
    {
      code: 'STREAK_7',
      category: 'streak',
      icon: 'local_fire_department',
      color: '#FF5722',
      conditionType: 'streak',
      conditionValue: 7,
      rarity: 'COMMON',
      sortOrder: 11,
      en: { name: '7-Day Warrior', description: 'Maintain a 7-day streak' },
      vi: { name: 'Chiến binh 7 ngày', description: 'Duy trì streak 7 ngày' },
    },
    {
      code: 'STREAK_14',
      category: 'streak',
      icon: 'whatshot',
      color: '#FF5722',
      conditionType: 'streak',
      conditionValue: 14,
      rarity: 'RARE',
      sortOrder: 12,
      en: { name: '2-Week Champion', description: 'Maintain a 14-day streak' },
      vi: { name: 'Nhà vô địch 2 tuần', description: 'Duy trì streak 14 ngày' },
    },
    {
      code: 'STREAK_30',
      category: 'streak',
      icon: 'whatshot',
      color: '#E91E63',
      conditionType: 'streak',
      conditionValue: 30,
      rarity: 'RARE',
      sortOrder: 13,
      en: { name: 'Monthly Master', description: 'Maintain a 30-day streak' },
      vi: { name: 'Bậc thầy tháng', description: 'Duy trì streak 30 ngày' },
    },
    {
      code: 'STREAK_50',
      category: 'streak',
      icon: 'bolt',
      color: '#E91E63',
      conditionType: 'streak',
      conditionValue: 50,
      rarity: 'EPIC',
      sortOrder: 14,
      en: { name: 'Unstoppable', description: 'Maintain a 50-day streak' },
      vi: { name: 'Không thể ngăn', description: 'Duy trì streak 50 ngày' },
    },
    {
      code: 'STREAK_100',
      category: 'streak',
      icon: 'diamond',
      color: '#FFD700',
      conditionType: 'streak',
      conditionValue: 100,
      rarity: 'LEGENDARY',
      sortOrder: 15,
      en: { name: 'Legend', description: 'Maintain a 100-day streak' },
      vi: { name: 'Huyền thoại', description: 'Duy trì streak 100 ngày' },
    },
    // EP badges
    {
      code: 'EP_500',
      category: 'ep',
      icon: 'stars',
      color: '#FFC107',
      conditionType: 'total_ep',
      conditionValue: 500,
      rarity: 'COMMON',
      sortOrder: 20,
      en: { name: 'Rising Star', description: 'Earn 500 EP total' },
      vi: { name: 'Ngôi sao mới', description: 'Tích lũy 500 EP' },
    },
    {
      code: 'EP_1000',
      category: 'ep',
      icon: 'stars',
      color: '#FFC107',
      conditionType: 'total_ep',
      conditionValue: 1000,
      rarity: 'COMMON',
      sortOrder: 21,
      en: { name: '1K Club', description: 'Earn 1,000 EP total' },
      vi: { name: 'CLB 1K', description: 'Tích lũy 1.000 EP' },
    },
    {
      code: 'EP_5000',
      category: 'ep',
      icon: 'auto_awesome',
      color: '#9C27B0',
      conditionType: 'total_ep',
      conditionValue: 5000,
      rarity: 'RARE',
      sortOrder: 22,
      en: { name: 'EP Master', description: 'Earn 5,000 EP total' },
      vi: { name: 'Bậc thầy EP', description: 'Tích lũy 5.000 EP' },
    },
    {
      code: 'EP_10000',
      category: 'ep',
      icon: 'auto_awesome',
      color: '#FF9800',
      conditionType: 'total_ep',
      conditionValue: 10000,
      rarity: 'EPIC',
      sortOrder: 23,
      en: { name: '10K Elite', description: 'Earn 10,000 EP total' },
      vi: { name: 'Elite 10K', description: 'Tích lũy 10.000 EP' },
    },
    {
      code: 'EP_50000',
      category: 'ep',
      icon: 'diamond',
      color: '#FFD700',
      conditionType: 'total_ep',
      conditionValue: 50000,
      rarity: 'LEGENDARY',
      sortOrder: 24,
      en: { name: 'EP Titan', description: 'Earn 50,000 EP total' },
      vi: { name: 'Titan EP', description: 'Tích lũy 50.000 EP' },
    },
    // Special badges
    {
      code: 'PERFECT_1',
      category: 'special',
      icon: 'done_all',
      color: '#4CAF50',
      conditionType: 'perfect_days',
      conditionValue: 1,
      rarity: 'COMMON',
      sortOrder: 30,
      en: { name: 'Perfect Day', description: 'Achieve your first Perfect Day' },
      vi: { name: 'Ngày hoàn hảo', description: 'Đạt Perfect Day đầu tiên' },
    },
    {
      code: 'PERFECT_7',
      category: 'special',
      icon: 'verified',
      color: '#9C27B0',
      conditionType: 'perfect_days',
      conditionValue: 7,
      rarity: 'RARE',
      sortOrder: 31,
      en: { name: 'Perfect Week', description: 'Achieve 7 Perfect Days' },
      vi: { name: 'Tuần hoàn hảo', description: 'Đạt 7 Perfect Day' },
    },
    {
      code: 'PERFECT_30',
      category: 'special',
      icon: 'shield',
      color: '#FF9800',
      conditionType: 'perfect_days',
      conditionValue: 30,
      rarity: 'EPIC',
      sortOrder: 32,
      en: { name: 'Perfect Month', description: 'Achieve 30 Perfect Days' },
      vi: { name: 'Tháng hoàn hảo', description: 'Đạt 30 Perfect Day' },
    },
    {
      code: 'POWER_SESSION',
      category: 'special',
      icon: 'flash_on',
      color: '#FF5722',
      conditionType: 'single_session_ep',
      conditionValue: 500,
      rarity: 'RARE',
      sortOrder: 33,
      en: { name: 'Power Session', description: 'Earn 500+ EP in a single session' },
      vi: { name: 'Phiên mạnh', description: 'Kiếm 500+ EP trong 1 phiên' },
    },
    {
      code: 'MEGA_SESSION',
      category: 'special',
      icon: 'flash_on',
      color: '#FFD700',
      conditionType: 'single_session_ep',
      conditionValue: 1000,
      rarity: 'EPIC',
      sortOrder: 34,
      en: { name: 'Mega Session', description: 'Earn 1,000+ EP in a single session' },
      vi: { name: 'Phiên siêu cấp', description: 'Kiếm 1.000+ EP trong 1 phiên' },
    },
  ];

  for (const badge of badges) {
    const { en, vi, ...badgeData } = badge;

    await prisma.badgeDefinition.upsert({
      where: { code: badgeData.code },
      update: {},
      create: {
        ...badgeData,
        translations: {
          create: [
            { locale: 'en', ...en },
            { locale: 'vi', ...vi },
          ],
        },
      },
    });
  }

  console.log(`Seeded ${badges.length} badge definitions`);
}
