// Mocks generated by Mockito 5.4.6 from annotations
// in ergo_life_app/test/blocs/achievement/achievement_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ergo_life_app/core/errors/failures.dart' as _i5;
import 'package:ergo_life_app/data/models/badge_model.dart' as _i6;
import 'package:ergo_life_app/data/repositories/achievement_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AchievementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAchievementRepository extends _i1.Mock
    implements _i3.AchievementRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>> getAllBadges() =>
      (super.noSuchMethod(
            Invocation.method(#getAllBadges, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.BadgeModel>>(
                    this,
                    Invocation.method(#getAllBadges, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.BadgeModel>>(
                    this,
                    Invocation.method(#getAllBadges, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>> getMyBadges() =>
      (super.noSuchMethod(
            Invocation.method(#getMyBadges, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.BadgeModel>>(
                    this,
                    Invocation.method(#getMyBadges, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.BadgeModel>>(
                    this,
                    Invocation.method(#getMyBadges, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.BadgeModel>>>);
}
