// Mocks generated by Mockito 5.4.6 from annotations
// in ergo_life_app/test/blocs/daily_goal/daily_goal_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:ergo_life_app/core/errors/failures.dart' as _i5;
import 'package:ergo_life_app/data/models/daily_goal_model.dart' as _i6;
import 'package:ergo_life_app/data/repositories/daily_goal_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DailyGoalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDailyGoalRepository extends _i1.Mock
    implements _i3.DailyGoalRepository {
  MockDailyGoalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.DailyGoalModel>> getTodayGoal() =>
      (super.noSuchMethod(
            Invocation.method(#getTodayGoal, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.DailyGoalModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.DailyGoalModel>(
                    this,
                    Invocation.method(#getTodayGoal, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.DailyGoalModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GoalSettingsModel>>
  getGoalSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getGoalSettings, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.GoalSettingsModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.GoalSettingsModel>(
                    this,
                    Invocation.method(#getGoalSettings, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.GoalSettingsModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.GoalSettingsModel>> updateGoalSettings(
    _i6.GoalSettingsModel? settings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateGoalSettings, [settings]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.GoalSettingsModel>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.GoalSettingsModel>(
                    this,
                    Invocation.method(#updateGoalSettings, [settings]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.GoalSettingsModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.DailyGoalModel>>> getGoalHistory({
    String? from,
    String? to,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getGoalHistory, [], {#from: from, #to: to}),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.DailyGoalModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.DailyGoalModel>>(
                    this,
                    Invocation.method(#getGoalHistory, [], {
                      #from: from,
                      #to: to,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.DailyGoalModel>>>);
}
